### ISSUE TITLE
Integration with AA

### ISSUE THREAD

**Issue by msdundar** [javierjulio/jsoneditor-rails#1]
Hi Javier,

How do you integrate this GEM with active admin? Can you please document it on Readme?

Thanks!

**Comment by javierjulio** [comment]
@msdundar I'm glad you asked! I created this gem because I actually needed it for ActiveAdmin. I've been meaning to write a blog post about this haha but didn't get around to it. Follow the installation instructions in the README and then do the following for ActiveAdmin support, assuming you already have a model with a jsonb column type.

1. Create a custom Formtastic input (this is a textarea) that will later render the JSON Editor:

    ```ruby
    # app/admin/inputs/jsonb_input.rb

    class JsonbInput < Formtastic::Inputs::TextInput

      def current_value
        (object.public_send(method) || {}).to_json
      end

      def input_html_options
        { value: current_value, class: 'js-jsoneditor' }.merge(super)
      end

      def to_html
        input_wrapping do
          label_html << builder.text_area(method, input_html_options)
        end
      end

    end
    ```

    Note the `.js-jsoneditor` class name which is the hook I use from JS to initialize the JSON Editor. 

2. [Create an attribute using Rails 5 Attributes API for jsonb support](http://til.obiefernandez.com/posts/8c31a92080-rails-5-attributes-api-jsonb-postgres-columns
)
3. Write the necessary JS that finds the input and [initializes the JSON Editor](https://github.com/josdejong/jsoneditor/blob/master/docs/usage.md#use)

**Comment by msdundar** [comment]
@javierjulio thank you very much!

**Comment by mulander** [comment]
Note for anyone else stumbling on this. This works, however I had to initialize the json editor on the **parent** record of `.js-jsoneditor` field. If initialized directly on the editor - the text area would cover the class. I also made the normal textarea invisible by adding the `hide` class to it.

Here is a sample coffeescript for initialization in rails5:

```coffeescript
   $ ->                                                                                                        
     if $('.js-jsoneditor').length                                                                             
       $('.js-jsoneditor').each (idx, item) =>                                                                                                                                                
         options = { mode: 'tree' }                                                                            
         editor = new JSONEditor(item.parentNode, options)                                                     
         editor.set(JSON.parse(item.value)) 
```

**Comment by javierjulio** [comment]
I've moved [my earlier example to the wiki](https://github.com/javierjulio/jsoneditor-rails/wiki/ActiveAdmin-Integration) so I'll close this out. Thanks everyone!
