### ISSUE TITLE
Change sass-rails dependency to sassc-rails?

### ISSUE THREAD

**Issue by mjrudowsky** [javierjulio/jsoneditor-rails#6]
sass-rails uses Ruby sass which is being deprecated in 26 March 2019 (http://sass.logdown.com/posts/7081811). Any thoughts of switching this project over to its replacement sassc-rails?

**Comment by javierjulio** [comment]
Yes I've been wondering what to do. We could switch it over but then I realized we don't have dependencies for other asset types like JS or images. I wonder if it might be better to just remove the dependency in a major release and in the installation instructions note that you have to have either `sass-rails` or `sassc-rails` in your Gemfile. What do you think? I think this would be ideal since that way you can choose now rather than let the library define it. Also `sass-rails` will be default be listed in any Rails generated Gemfile so it should be good.

**Comment by mjrudowsky** [comment]
I would be fine with removing the dependency and changing the installation instructions. Your reasoning makes sense to me. I had already changed my Gemfile to point to sassc-rails, so I'm already prepared.

**Comment by Pectojin** [comment]
Any news on this? The deadline is nearing rapidly.

**Comment by javierjulio** [comment]
Yes. I choose not to do anything because I found out that the plan is likely you won't have to make any changes. The sass-rails gem will be updated to use sassc under the hood.

https://github.com/activeadmin/activeadmin/pull/5504#issuecomment-456839445
https://github.com/rails/sass-rails/pull/424

**Comment by javierjulio** [comment]
I updated master so this gem no longer depends on sass-rails but instead on railties.

In the end everything has been fine since sass-rails was released as just a light wrapper around sassc-rails anyway.
